import type { ColumnInfo } from "../../../api/db";
import type { SelectedTable } from "./types";

export const buildDefaultQuery = (selected: SelectedTable | null) => {
  if (!selected) {
    return "SELECT 1;";
  }

  return `SELECT *\nFROM ${selected.table}\nLIMIT 200;`;
};

export const isAutoGeneratedColumn = (column: ColumnInfo) =>
  column.extra?.includes("auto_increment") || column.column_default?.includes("nextval");

export const getLiteralDefaultValue = (column: ColumnInfo) => {
  if (!column.column_default) {
    return "";
  }

  let value = column.column_default.trim();
  if (!value) {
    return "";
  }

  const lower = value.toLowerCase();
  if (lower === "null" || lower.startsWith("current_")) {
    return "";
  }

  if (lower.includes("nextval") || lower.includes("gen_random_uuid") || lower.includes("uuid_generate")) {
    return "";
  }

  if (value.includes("(")) {
    return "";
  }

  if (value.includes("::")) {
    value = value.split("::")[0].trim();
  }

  if (value.startsWith("'") && value.endsWith("'") && value.length >= 2) {
    return value.slice(1, -1).replace(/''/g, "'");
  }

  if (/^-?\d+(\.\d+)?$/.test(value)) {
    return value;
  }

  if (lower === "true" || lower === "false") {
    return lower;
  }

  return "";
};

export const buildInsertDefaults = (columns: ColumnInfo[]) => {
  const defaults: Record<string, string> = {};

  columns.forEach((column) => {
    if (isAutoGeneratedColumn(column)) {
      return;
    }

    const defaultValue = getLiteralDefaultValue(column);
    if (defaultValue !== "") {
      defaults[column.column_name] = defaultValue;
    }
  });

  return defaults;
};
