import { useEffect, useMemo, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { FaSyncAlt } from "react-icons/fa";
import { fetchConnections, ConnectionsResponse, DatabaseConnection } from "../api/connections";
import { ExplorerSchema, fetchSourceExplorer, fetchTablePreview, fetchTableStructure, runSourceSql, insertTableRow, ColumnInfo } from "../api/db";
import { createRequestFolder, createSqlRequest, fetchRequestLibrary, RequestFolder, SqlRequest, updateRequestFolder, updateSqlRequest, deleteRequestFolder, deleteSqlRequest } from "../api/requests";
import DatabaseEmptyState from "../components/Database/DatabaseEmptyState";
import DatabaseTopBar from "../components/Database/DatabaseTopBar";
import InsertPanel from "../components/Database/InsertPanel";
import RequestsPanel, {
  RequestContextMenuState,
  RequestInlineEditingItem,
  RequestRenamingItem,
} from "../components/Database/RequestsPanel";
import SearchPanel from "../components/Database/SearchPanel";
import SourcesPanel from "../components/Database/SourcesPanel";
import StructurePanel from "../components/Database/StructurePanel";
import TablesPanel from "../components/Database/TablesPanel";
import { buildDefaultQuery, buildInsertDefaults, getLiteralDefaultValue, isAutoGeneratedColumn } from "../components/Database/tableUtils";
import {
  persistLeftPanelTab,
  persistSource,
  persistSql,
  persistTable,
  readPersistedLeftPanelTab,
  readPersistedSource,
  readPersistedSql,
  readPersistedTable,
} from "../components/Database/storage";
import { LeftPanelTab, SelectedTable, SortDirection, ViewPanelContent } from "../components/Database/types";
import IconButton from "../ui/IconButton";
import CollapsibleSection from "../ui/CollapsibleSection";

type MonacoEditorApi = typeof import("monaco-editor");
type MonacoCodeEditor = import("monaco-editor").editor.IStandaloneCodeEditor;

const DatabasePage = () => {
  const initialLeftPanelTab = readPersistedLeftPanelTab();
  const navigate = useNavigate();
  const { sourceId } = useParams<{ sourceId?: string }>();
  const [connections, setConnections] = useState<ConnectionsResponse>({ db: [], ssh: [] });
  const [isLoadingConnections, setIsLoadingConnections] = useState(false);
  const [connectionsError, setConnectionsError] = useState("");
  const [existingQuery, setExistingQuery] = useState("");
  const [selectedDatabase, setSelectedDatabase] = useState<DatabaseConnection | null>(null);
  const [selectedTable, setSelectedTable] = useState<SelectedTable | null>(null);
  const [explorerSchemas, setExplorerSchemas] = useState<ExplorerSchema[]>([]);
  const [isLoadingExplorer, setIsLoadingExplorer] = useState(false);
  const [explorerError, setExplorerError] = useState("");
  const [schemaFilter, setSchemaFilter] = useState("");
  const [requestFilter, setRequestFilter] = useState("");
  const [requestFolders, setRequestFolders] = useState<RequestFolder[]>([]);
  const [requestItems, setRequestItems] = useState<SqlRequest[]>([]);
  const [isLoadingRequests, setIsLoadingRequests] = useState(false);
  const [requestsError, setRequestsError] = useState("");
  const [selectedRequestId, setSelectedRequestId] = useState<string | null>(null);

  const [sqlText, setSqlText] = useState(() => readPersistedSql());
  const [resultColumns, setResultColumns] = useState<string[]>([]);
  const [resultRows, setResultRows] = useState<Record<string, unknown>[]>([]);
  const [isLoadingResult, setIsLoadingResult] = useState(false);
  const [resultError, setResultError] = useState("");
  const [resultMeta, setResultMeta] = useState("");
  const [resultSource, setResultSource] = useState<"preview" | "sql" | null>(null);
  const [leftPanelTab, setLeftPanelTab] = useState<LeftPanelTab>(initialLeftPanelTab);
  const [showSqlPanel, setShowSqlPanel] = useState(true);
  const [expandSqlPanel, setExpandSqlPanel] = useState(true);
  const [editorHeight, setEditorHeight] = useState(144); // Default 9rem (144px)
  const [showViewPanel, setShowViewPanel] = useState(false);
  const [viewPanelContent, setViewPanelContent] = useState<ViewPanelContent>(null);
  const [structureColumns, setStructureColumns] = useState<ColumnInfo[]>([]);
  const [isLoadingStructure, setIsLoadingStructure] = useState(false);
  const [structureError, setStructureError] = useState("");
  const [insertFormData, setInsertFormData] = useState<Record<string, string>>({});
  const [isInserting, setIsInserting] = useState(false);
  const [insertError, setInsertError] = useState("");
  const [insertSuccess, setInsertSuccess] = useState(false);
  const [searchFilters, setSearchFilters] = useState<Record<string, { operator: string; value: string }>>({});
  const [isSearching, setIsSearching] = useState(false);
  const [searchError, setSearchError] = useState("");
  const [selectedRowIndices, setSelectedRowIndices] = useState<Set<number>>(new Set());
  const [contextMenu, setContextMenu] = useState<{ x: number; y: number; rowIndex: number } | null>(null);
  const [inlineEditingItem, setInlineEditingItem] = useState<RequestInlineEditingItem | null>(null);
  const [inlineEditingValue, setInlineEditingValue] = useState("");
  const [renamingItem, setRenamingItem] = useState<RequestRenamingItem | null>(null);
  const [requestContextMenu, setRequestContextMenu] = useState<RequestContextMenuState | null>(null);
  const [isDeleting, setIsDeleting] = useState(false);
  const [isDeleteConfirming, setIsDeleteConfirming] = useState(false);
  const [tableSort, setTableSort] = useState<{ column: string; direction: SortDirection } | null>(null);
  const [editingRowIndex, setEditingRowIndex] = useState<number | null>(null);
  const [editingCell, setEditingCell] = useState<{ rowIndex: number; column: string } | null>(null);
  const [editingCellValue, setEditingCellValue] = useState("");
  const [isInlineUpdating, setIsInlineUpdating] = useState(false);
  const selectAllCheckboxRef = useRef<HTMLInputElement>(null);
  const insertPrefillRef = useRef(false);
  const monacoContainerRef = useRef<HTMLDivElement | null>(null);
  const monacoEditorRef = useRef<MonacoCodeEditor | null>(null);
  const monacoApiRef = useRef<MonacoEditorApi | null>(null);
  const runSqlRef = useRef<() => void>(() => undefined);
  const structureCacheRef = useRef<{
    key: string;
    columns: ColumnInfo[];
  } | null>(null);

  const loadConnections = async () => {
    setIsLoadingConnections(true);
    setConnectionsError("");

    try {
      const data = await fetchConnections();
      setConnections(data);

      if (sourceId !== undefined) {
        if (!sourceId) {
          setSelectedDatabase(null);
          setConnectionsError("Invalid database source id in URL.");
          return;
        }

        const fromUrl = data.db.find((item) => item.db_id === sourceId);
        if (!fromUrl) {
          setSelectedDatabase(null);
          setConnectionsError("Database source not found.");
          return;
        }

        setSelectedDatabase(fromUrl);
        persistSource(fromUrl);
        return;
      }

      const persisted = readPersistedSource();
      if (!persisted) {
        setSelectedDatabase(null);
        return;
      }

      const restored = data.db.find((item) => {
        if (persisted.id !== null && item.db_id !== null) {
          return item.db_id === persisted.id;
        }
        return item.name === persisted.name;
      });

      if (restored) {
        setSelectedDatabase(restored);
        if (restored.db_id !== null) {
          navigate(`/database/${restored.db_id}`, { replace: true });
        }
      } else {
        setSelectedDatabase(null);
      }
    } catch (error) {
      console.error("Error fetching connections:", error);
      setConnectionsError("Unable to load connections.");
    } finally {
      setIsLoadingConnections(false);
    }
  };

  useEffect(() => {
    loadConnections();
  }, [sourceId]);

  useEffect(() => {
    const loadExplorer = async () => {
      if (!selectedDatabase) {
        setExplorerSchemas([]);
        setExplorerError("");
        return;
      }

      if (!selectedDatabase.db_id) {
        setExplorerSchemas([]);
        setExplorerError("Selected source does not have a valid id.");
        return;
      }

      setIsLoadingExplorer(true);
      setExplorerError("");

      try {
        const data = await fetchSourceExplorer(selectedDatabase.db_id);
        setExplorerSchemas(data.schemas);
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unable to load schemas and tables.";
        setExplorerSchemas([]);
        setExplorerError(message);
      } finally {
        setIsLoadingExplorer(false);
      }
    };

    loadExplorer();
  }, [selectedDatabase]);

  useEffect(() => {
    const loadRequests = async () => {
      if (!selectedDatabase?.db_id) {
        setRequestFolders([]);
        setRequestItems([]);
        setRequestsError("");
        setSelectedRequestId(null);
        return;
      }

      setIsLoadingRequests(true);
      setRequestsError("");

      try {
        const data = await fetchRequestLibrary(selectedDatabase.db_id);
        setRequestFolders(data.folders);
        setRequestItems(data.requests);
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unable to load requests.";
        setRequestFolders([]);
        setRequestItems([]);
        setRequestsError(message);
      } finally {
        setIsLoadingRequests(false);
      }
    };

    loadRequests();
  }, [selectedDatabase?.db_id]);

  // Immediately clear selected table when database changes (before validation)
  // This prevents stale table selection from querying old database
  useEffect(() => {
    setSelectedTable(null);
    structureCacheRef.current = null;
  }, [selectedDatabase?.db_id]);

  useEffect(() => {
    if (!selectedDatabase || explorerSchemas.length === 0) {
      setSelectedTable(null);
      return;
    }

    setSelectedTable((previous) => {
      // If already have a selection, validate it still exists in current database
      if (previous) {
        const schemaExists = explorerSchemas.some(
          (schema) => schema.name === previous.schema && schema.tables.some((table) => table.name === previous.table),
        );

        if (schemaExists) {
          return previous;
        }
        // Table doesn't exist in new database, clear selection
        return null;
      }

      // Try to restore from localStorage only if valid in current database
      const persisted = readPersistedTable(selectedDatabase.db_id);
      if (persisted) {
        const schemaExists = explorerSchemas.some(
          (schema) => schema.name === persisted.schema && schema.tables.some((table) => table.name === persisted.table),
        );
        if (schemaExists) {
          return persisted;
        }
      }

      // Don't auto-select - let user pick first table
      return null;
    });
  }, [selectedDatabase, explorerSchemas]);

  useEffect(() => {
    // Only update SQL if no custom query exists and a table is selected
    if (selectedTable && sqlText === "SELECT 1;") {
      setSqlText(buildDefaultQuery(selectedTable));
    }
  }, [selectedTable?.schema, selectedTable?.table]);

  useEffect(() => {
    // Persist SQL query whenever it changes
    persistSql(sqlText);
  }, [sqlText]);

  useEffect(() => {
    persistLeftPanelTab(leftPanelTab);
  }, [leftPanelTab]);

  useEffect(() => {
    // Persist selected table whenever it changes
    if (selectedDatabase?.db_id) {
      persistTable(selectedDatabase.db_id, selectedTable);
    }
    
    // Clear structure cache when table changes
    structureCacheRef.current = null;
    
    // Close view panel when table changes
    if (selectedTable) {
      setShowViewPanel(false);
      setViewPanelContent(null);
    }
  }, [selectedDatabase?.db_id, selectedTable]);

  useEffect(() => {
    if (!selectedDatabase) {
      setLeftPanelTab("sources");
    }
  }, [selectedDatabase]);

  // Immediately clear results when database changes to prevent stale data display
  useEffect(() => {
    setResultColumns([]);
    setResultRows([]);
    setResultError("");
    setResultMeta("");
  }, [selectedDatabase?.db_id]);

  useEffect(() => {
    let disposed = false;
    let updateHeightFn: (() => void) | null = null;

    const mountEditor = async () => {
      if (!selectedDatabase || !showSqlPanel || !expandSqlPanel || !monacoContainerRef.current || monacoEditorRef.current) {
        return;
      }

      const monaco = await import("monaco-editor");
      if (disposed || !monacoContainerRef.current) {
        return;
      }

      monacoApiRef.current = monaco;
      monaco.editor.defineTheme("polarstar-sql", {
        base: "vs-dark",
        inherit: true,
        rules: [],
        colors: {
          "editor.background": "#00000080",
        },
      });

      const editor = monaco.editor.create(monacoContainerRef.current, {
        value: sqlText,
        language: "sql",
        theme: "polarstar-sql",
        automaticLayout: true,
        minimap: { enabled: true },
        wordWrap: "on",
        scrollBeyondLastLine: false,
        fontSize: 12,
        lineHeight: 18,
        scrollbar: {
          verticalScrollbarSize: 8,
          horizontalScrollbarSize: 8,
        },
      });

      const updateEditorHeight = () => {
        const contentHeight = editor.getContentHeight() + 20; // Add some padding
        const maxHeight = Math.floor(window.innerHeight * (2 / 3)); // 2/3 of screen height
        const minHeight = 18 * 10;
        const newHeight = Math.min(Math.max(contentHeight, minHeight), maxHeight);
        setEditorHeight(newHeight);
      };

      updateHeightFn = updateEditorHeight;

      editor.onDidChangeModelContent(() => {
        setSqlText(editor.getValue());
        updateEditorHeight();
      });

      editor.onDidContentSizeChange(() => {
        updateEditorHeight();
      });

      // Initial height calculation
      updateEditorHeight();

      // Handle window resize for max height recalculation
      window.addEventListener('resize', updateEditorHeight);

      editor.addCommand(monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter, () => {
        runSqlRef.current();
      });

      monacoEditorRef.current = editor;
    };

    mountEditor();

    return () => {
      disposed = true;
      if (updateHeightFn) {
        window.removeEventListener('resize', updateHeightFn);
      }
      if (monacoEditorRef.current) {
        monacoEditorRef.current.dispose();
        monacoEditorRef.current = null;
      }
    };
  }, [selectedDatabase, showSqlPanel, expandSqlPanel]);

  useEffect(() => {
    const editor = monacoEditorRef.current;
    if (!editor) {
      return;
    }

    if (editor.getValue() !== sqlText) {
      editor.setValue(sqlText);
    }
  }, [sqlText]);

  const previewRows = useMemo(
    () => resultRows,
    [resultRows],
  );

  const canDeleteRows = Boolean(selectedTable && resultSource === "preview" && resultRows.length > 0);

  const hotColumns = useMemo(
    () => (resultColumns.length > 0 ? resultColumns : previewRows.length > 0 ? Object.keys(previewRows[0]) : []),
    [resultColumns, previewRows],
  );

  const filteredSchemas = useMemo(() => {
    if (!schemaFilter.trim()) {
      return explorerSchemas;
    }

    const query = schemaFilter.toLowerCase().trim();
    return explorerSchemas
      .map((schema) => ({
        ...schema,
        tables: schema.tables.filter((table) =>
          table.name.toLowerCase().includes(query) || schema.name.toLowerCase().includes(query)
        ),
      }))
      .filter((schema) => schema.name.toLowerCase().includes(query) || schema.tables.length > 0);
  }, [explorerSchemas, schemaFilter]);

  const filteredRequestItems = useMemo(() => {
    if (!requestFilter.trim()) {
      return requestItems;
    }

    const query = requestFilter.toLowerCase().trim();
    return requestItems.filter((request) =>
      request.request_name.toLowerCase().includes(query) || request.sql_text.toLowerCase().includes(query)
    );
  }, [requestItems, requestFilter]);

  const requestsByFolder = useMemo(() => {
    const map = new Map<string, SqlRequest[]>();
    filteredRequestItems.forEach((request) => {
      const key = request.request_folder_id || "ungrouped";
      const existing = map.get(key);
      if (existing) {
        existing.push(request);
      } else {
        map.set(key, [request]);
      }
    });
    return map;
  }, [filteredRequestItems]);

  const filteredRequestFolders = useMemo(() => {
    if (!requestFilter.trim()) {
      return requestFolders;
    }

    const query = requestFilter.toLowerCase().trim();
    return requestFolders.filter((folder) => {
      const matchesFolder = folder.folder_name.toLowerCase().includes(query);
      const hasRequests = (requestsByFolder.get(folder.request_folder_id) || []).length > 0;
      return matchesFolder || hasRequests;
    });
  }, [requestFolders, requestFilter, requestsByFolder]);

  const ungroupedRequests = useMemo(
    () => requestsByFolder.get("ungrouped") || [],
    [requestsByFolder]
  );

  const selectedRowKey = useMemo(
    () => [...selectedRowIndices].sort((a, b) => a - b).join(","),
    [selectedRowIndices]
  );

  useEffect(() => {
    const abortController = new AbortController();

    const loadPreviewRows = async () => {
      // Clear results if no table selected
      if (!selectedTable?.schema || !selectedTable?.table) {
        if (resultSource === "preview") {
          setResultColumns([]);
          setResultRows([]);
          setResultError("");
          setResultMeta("");
          setResultSource(null);
        }
        return;
      }

      // Only load if we have a database selected
      if (!selectedDatabase?.db_id) {
        return;
      }

      // Validate that the table exists in current database schemas
      const tableExists = explorerSchemas.some(
        (schema) => schema.name === selectedTable.schema && schema.tables.some((table) => table.name === selectedTable.table),
      );

      if (!tableExists) {
        // Table doesn't exist in current database, clear results
        setResultColumns([]);
        setResultRows([]);
        setResultError("");
        setResultMeta("");
        return;
      }

      setIsLoadingResult(true);
      setResultError("");

      try {
        const preview = await fetchTablePreview(selectedDatabase.db_id, selectedTable.schema, selectedTable.table, 200);
        
        // Only update state if request wasn't aborted
        if (!abortController.signal.aborted) {
          setResultColumns(preview.columns);
          setResultRows(preview.rows);
          setResultMeta(`Preview • ${preview.rowCount} rows`);
          setResultSource("preview");
        }
      } catch (error) {
        // Don't update state if request was aborted
        if (abortController.signal.aborted) {
          return;
        }
        
        const message = error instanceof Error ? error.message : "Unable to load table preview.";
        setResultColumns([]);
        setResultRows([]);
        setResultMeta("");
        setResultError(message);
        setResultSource(null);
      } finally {
        if (!abortController.signal.aborted) {
          setIsLoadingResult(false);
        }
      }
    };

    loadPreviewRows();

    return () => {
      abortController.abort();
    };
  }, [selectedDatabase?.db_id, selectedTable?.schema, selectedTable?.table, explorerSchemas]);

  useEffect(() => {
    const loadStructure = async () => {
      // Load structure for structure, insert, and search views
      if (!viewPanelContent || !selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table) {
        return;
      }

      // Build cache key
      const cacheKey = `${selectedDatabase.db_id}:${selectedTable.schema}:${selectedTable.table}`;
      
      // Check if we have cached structure for this table
      if (structureCacheRef.current?.key === cacheKey) {
        // Use cached structure
        setStructureColumns(structureCacheRef.current.columns);
        setStructureError("");
        
        // Initialize insert form with cached columns unless prefilled
        if (viewPanelContent === "insert") {
          if (insertPrefillRef.current) {
            insertPrefillRef.current = false;
          } else {
            const initialFormData = buildInsertDefaults(structureCacheRef.current.columns);
            setInsertFormData(initialFormData);
          }
          setInsertError("");
          setInsertSuccess(false);
        }
        
        // Initialize search filters
        if (viewPanelContent === "search") {
          setSearchFilters({});
          setSearchError("");
        }
        
        return; // Skip fetching
      }

      setIsLoadingStructure(true);
      setStructureError("");

      try {
        const structure = await fetchTableStructure(selectedDatabase.db_id, selectedTable.schema, selectedTable.table);
        setStructureColumns(structure.columns);
        
        // Cache the structure
        structureCacheRef.current = {
          key: cacheKey,
          columns: structure.columns
        };
        
        // Initialize insert form with empty values unless prefilled
        if (viewPanelContent === "insert") {
          if (insertPrefillRef.current) {
            insertPrefillRef.current = false;
          } else {
            const initialFormData = buildInsertDefaults(structure.columns);
            setInsertFormData(initialFormData);
          }
          setInsertError("");
          setInsertSuccess(false);
        }
        
        // Initialize search filters
        if (viewPanelContent === "search") {
          setSearchFilters({});
          setSearchError("");
        }
      } catch (error) {
        const message = error instanceof Error ? error.message : "Unable to load table structure.";
        setStructureColumns([]);
        setStructureError(message);
      } finally {
        setIsLoadingStructure(false);
      }
    };

    loadStructure();
  }, [viewPanelContent, selectedDatabase?.db_id, selectedTable?.schema, selectedTable?.table]);

  const handleInsertFormChange = (columnName: string, value: string) => {
    setInsertFormData(prev => ({
      ...prev,
      [columnName]: value
    }));
  };

  const handleInsertSubmit = async () => {
    if (!selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table) {
      setInsertError("No table selected.");
      return;
    }

    setIsInserting(true);
    setInsertError("");
    setInsertSuccess(false);

    try {
      if (editingRowIndex !== null) {
        // Update mode - generate UPDATE query
        const originalRow = previewRows[editingRowIndex] as Record<string, unknown>;
        const setClauses: string[] = [];
        const whereClauses: string[] = [];

        // Build SET clause from current form data
        Object.entries(insertFormData).forEach(([col, val]) => {
          const quoted = val.replace(/'/g, "''");
          setClauses.push(`\`${col}\` = '${quoted}'`);
        });

        // Build WHERE clause from original row data
        Object.entries(originalRow).forEach(([col, val]) => {
          if (val === null || val === undefined) {
            whereClauses.push(`\`${col}\` IS NULL`);
          } else {
            const quoted = String(val).replace(/'/g, "''");
            whereClauses.push(`\`${col}\` = '${quoted}'`);
          }
        });

        if (setClauses.length > 0 && whereClauses.length > 0) {
          const updateQuery = `UPDATE \`${selectedTable.schema}\`.\`${selectedTable.table}\` SET ${setClauses.join(', ')} WHERE ${whereClauses.join(' AND ')}`;
          await runSourceSql(selectedDatabase.db_id, updateQuery);
        }
      } else {
        // Insert mode
        const insertPayload: Record<string, unknown> = {};
        structureColumns.forEach((column) => {
          if (isAutoGeneratedColumn(column)) {
            return;
          }

          const value = insertFormData[column.column_name];
          if (value === undefined) {
            return;
          }

          if (value === "") {
            const defaultValue = getLiteralDefaultValue(column);
            if (defaultValue !== "") {
              insertPayload[column.column_name] = defaultValue;
              return;
            }

            const dataType = column.data_type?.toLowerCase() || "";
            if (dataType.includes("uuid")) {
              if (column.column_default) {
                return;
              }

              if (column.is_nullable?.toLowerCase() === "yes") {
                insertPayload[column.column_name] = null;
                return;
              }

              return;
            }

            if (column.column_default) {
              // Let the database apply non-literal defaults like gen_random_uuid().
              return;
            }
          }

          insertPayload[column.column_name] = value;
        });

        await insertTableRow(
          selectedDatabase.db_id,
          selectedTable.schema,
          selectedTable.table,
          insertPayload
        );
      }
      
      setInsertSuccess(true);

      setInsertFormData(buildInsertDefaults(structureColumns));
      setEditingRowIndex(null);
      
      // Reload browse data if browse view was previously loaded
      if (resultRows.length > 0 && selectedDatabase?.db_id && selectedTable?.schema && selectedTable?.table) {
        const preview = await fetchTablePreview(selectedDatabase.db_id, selectedTable.schema, selectedTable.table, 200);
        setResultColumns(preview.columns);
        setResultRows(preview.rows);
        setResultMeta(`Preview • ${preview.rowCount} rows`);
      }
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to save row.";
      setInsertError(message);
    } finally {
      setIsInserting(false);
    }
  };

  const handleInsertReset = () => {
    const initialFormData = buildInsertDefaults(structureColumns);
    setInsertFormData(initialFormData);
    setInsertSuccess(false);
    setInsertError("");
    setEditingRowIndex(null);
  };

  const handleSearchFilterChange = (columnName: string, field: 'operator' | 'value', value: string) => {
    setSearchFilters(prev => ({
      ...prev,
      [columnName]: {
        ...prev[columnName],
        operator: field === 'operator' ? value : (prev[columnName]?.operator || '='),
        value: field === 'value' ? value : (prev[columnName]?.value || '')
      }
    }));
  };

  const handleClearSearchFilter = (columnName: string) => {
    setSearchFilters(prev => {
      const nextFilters = { ...prev };
      delete nextFilters[columnName];
      return nextFilters;
    });
  };

  const handleClearSearchAll = () => {
    setSearchFilters({});
    setSearchError("");
  };

  const handleSearchSubmit = async () => {
    if (!selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table) {
      setSearchError("No table selected.");
      return;
    }

    // Build WHERE clause from filters
    const conditions: string[] = [];
    Object.entries(searchFilters).forEach(([column, filter]) => {
      if (filter.value.trim()) {
        const quotedCol = `\`${column}\``;  // Quote identifier for safety
        if (filter.operator === 'LIKE') {
          conditions.push(`${quotedCol} LIKE '%${filter.value.replace(/'/g, "''")}%'`);
        } else if (filter.operator === 'IS NULL') {
          conditions.push(`${quotedCol} IS NULL`);
        } else if (filter.operator === 'IS NOT NULL') {
          conditions.push(`${quotedCol} IS NOT NULL`);
        } else {
          conditions.push(`${quotedCol} ${filter.operator} '${filter.value.replace(/'/g, "''")}'`);
        }
      }
    });

    if (conditions.length === 0) {
      setSearchError("Please add at least one filter condition.");
      return;
    }

    const whereClause = conditions.join(' AND ');
    const query = `SELECT * FROM \`${selectedTable.schema}\`.\`${selectedTable.table}\` WHERE ${whereClause} LIMIT 1000`;

    setIsSearching(true);
    setSearchError("");

    try {
      const result = await runSourceSql(selectedDatabase.db_id, query);
      // Update browse view with search results
      setResultColumns(result.columns);
      setResultRows(result.rows);
      setResultMeta(`${result.rowCount} rows found • ${result.durationMs !== undefined ? `${result.durationMs}ms` : ""}`);
      
      // Close search panel to show results
      setShowViewPanel(false);
      setViewPanelContent(null);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to execute search.";
      setSearchError(message);
    } finally {
      setIsSearching(false);
    }
  };

  const runSql = async (sqlOverride?: string) => {
    if (!selectedDatabase?.db_id) {
      setResultError("No source selected.");
      return;
    }

    setIsLoadingResult(true);
    setResultError("");

    try {
      const queryToRun = sqlOverride ?? sqlText;
      const result = await runSourceSql(selectedDatabase.db_id, queryToRun);
      setResultColumns(result.columns);
      setResultRows(result.rows);
      setResultMeta(`${result.command ?? "Query"} • ${result.rowCount} rows${result.durationMs !== undefined ? ` • ${result.durationMs}ms` : ""}`);
      setResultSource("sql");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to run SQL query.";
      setResultMeta("");
      setResultError(message);
      setResultSource(null);
    } finally {
      setIsLoadingResult(false);
    }
  };

  runSqlRef.current = runSql;

  const handleRefreshResults = async () => {
    if (resultSource === "sql") {
      await runSql();
      return;
    }

    await refreshPreviewRows();
  };

  const handleSelectRequest = (request: SqlRequest) => {
    setSelectedRequestId(request.request_id);
    setSqlText(request.sql_text);
    setShowSqlPanel(true);
    setExpandSqlPanel(true);
  };

  const handleCreateFolder = async (folderName: string) => {
    if (!selectedDatabase?.db_id) {
      setRequestsError("No source selected.");
      return;
    }

    if (!folderName.trim()) {
      setRequestsError("Folder name is required.");
      return;
    }

    setRequestsError("");

    try {
      const created = await createRequestFolder({
        db_id: selectedDatabase.db_id,
        folder_name: folderName.trim(),
        folder_description: null,
      });
      setRequestFolders((prev) => [...prev, created]);
      setInlineEditingItem(null);
      setInlineEditingValue("");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to create folder.";
      setRequestsError(message);
    }
  };

  const handleCreateRequest = async (requestName: string, parentFolderId: string | null = null) => {
    if (!selectedDatabase?.db_id) {
      setRequestsError("No source selected.");
      return;
    }

    if (!requestName.trim()) {
      setRequestsError("Request name is required.");
      return;
    }

    setRequestsError("");

    try {
      const created = await createSqlRequest({
        db_id: selectedDatabase.db_id,
        request_name: requestName.trim(),
        request_description: null,
        sql_text: sqlText || "SELECT 1;",
        request_folder_id: parentFolderId || null,
      });
      setRequestItems((prev) => [...prev, created]);
      setSelectedRequestId(created.request_id);
      setInlineEditingItem(null);
      setInlineEditingValue("");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to create request.";
      setRequestsError(message);
    }
  };

  const handleRenameFolder = async (folderId: string, newName: string) => {
    if (!newName.trim()) {
      setRequestsError("Folder name is required.");
      return;
    }

    try {
      const updated = await updateRequestFolder(folderId, {
        folder_name: newName.trim(),
      });
      setRequestFolders((prev) => prev.map((f) => (f.request_folder_id === folderId ? updated : f)));
      setRenamingItem(null);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to rename folder.";
      setRequestsError(message);
    }
  };

  const handleRenameRequest = async (requestId: string, newName: string) => {
    if (!newName.trim()) {
      setRequestsError("Request name is required.");
      return;
    }

    try {
      const updated = await updateSqlRequest(requestId, {
        request_name: newName.trim(),
      });
      setRequestItems((prev) => prev.map((r) => (r.request_id === requestId ? updated : r)));
      setRenamingItem(null);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to rename request.";
      setRequestsError(message);
    }
  };

  const handleDeleteFolder = async (folderId: string) => {
    try {
      await deleteRequestFolder(folderId);
      setRequestFolders((prev) => prev.filter((f) => f.request_folder_id !== folderId));
      // Also remove any requests that were in this folder
      setRequestItems((prev) => prev.filter((r) => r.request_folder_id !== folderId));
      setRequestContextMenu(null);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to delete folder.";
      setRequestsError(message);
    }
  };

  const handleDeleteRequest = async (requestId: string) => {
    try {
      await deleteSqlRequest(requestId);
      setRequestItems((prev) => prev.filter((r) => r.request_id !== requestId));
      if (selectedRequestId === requestId) {
        setSelectedRequestId(null);
      }
      setRequestContextMenu(null);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to delete request.";
      setRequestsError(message);
    }
  };

  const handleSelectTable = (schema: string, table: string) => {
    const nextTable = { schema, table };
    setSelectedTable(nextTable);
    setSqlText(buildDefaultQuery(nextTable));
  };

  const toggleRowSelection = (rowIndex: number) => {
    setSelectedRowIndices(prev => {
      const newSet = new Set(prev);
      if (newSet.has(rowIndex)) {
        newSet.delete(rowIndex);
      } else {
        newSet.add(rowIndex);
      }
      return newSet;
    });
  };

  const getCellDisplayValue = (value: unknown) => {
    if (value === null || value === undefined) {
      return "";
    }

    if (typeof value === "object") {
      return JSON.stringify(value);
    }

    return String(value);
  };

  const toSqlLiteral = (value: unknown) => {
    if (value === null || value === undefined) {
      return "NULL";
    }

    if (typeof value === "number" || typeof value === "bigint") {
      return String(value);
    }

    if (typeof value === "boolean") {
      return value ? "TRUE" : "FALSE";
    }

    const normalized = typeof value === "object" ? JSON.stringify(value) : String(value);
    return `'${normalized.replace(/'/g, "''")}'`;
  };

  const getSourceEngine = () => `${selectedDatabase?.engine || "postgres"}`.trim().toLowerCase();

  const quoteSqlIdentifier = (identifier: string) => {
    const engine = getSourceEngine();
    if (engine === "mysql" || engine === "mariadb") {
      return `\`${identifier.replace(/`/g, "``")}\``;
    }

    return `"${identifier.replace(/"/g, '""')}"`;
  };

  const buildSortedSql = (rawSql: string, column: string, direction: SortDirection) => {
    const fallbackSql = selectedTable ? buildDefaultQuery(selectedTable) : "SELECT 1;";
    const sourceSql = (rawSql || fallbackSql).trim();
    const queryBase = /^select\b/i.test(sourceSql) ? sourceSql : fallbackSql;
    const withoutSemicolon = queryBase.replace(/;\s*$/g, "").trim();

    const limitMatch = withoutSemicolon.match(/\s+LIMIT\s+\d+(\s+OFFSET\s+\d+)?\s*$/i);
    const limitClause = limitMatch ? limitMatch[0].trim() : "";
    const withoutLimit = limitMatch ? withoutSemicolon.slice(0, withoutSemicolon.length - limitMatch[0].length).trim() : withoutSemicolon;

    const withoutOrderBy = withoutLimit.replace(/\s+ORDER\s+BY\s+[\s\S]*$/i, "").trim();
    const orderByClause = `ORDER BY ${quoteSqlIdentifier(column)} ${direction.toUpperCase()}`;
    const nextSql = [withoutOrderBy, orderByClause, limitClause].filter(Boolean).join(" ").trim();

    return `${nextSql};`;
  };

  const handleSortByColumn = (column: string) => {
    if (!selectedTable) {
      return;
    }

    const direction: SortDirection =
      tableSort?.column === column && tableSort.direction === "asc" ? "desc" : "asc";

    setTableSort({ column, direction });
    const nextSql = buildSortedSql(sqlText, column, direction);
    setSqlText(nextSql);
    void runSql(nextSql);
  };

  const refreshPreviewRows = async () => {
    if (!selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table) {
      return;
    }

    setIsLoadingResult(true);
    setResultError("");

    try {
      const preview = await fetchTablePreview(selectedDatabase.db_id, selectedTable.schema, selectedTable.table, 200);
      setResultColumns(preview.columns);
      setResultRows(preview.rows);
      setResultMeta(`Preview • ${preview.rowCount} rows`);
      setResultSource("preview");
      setSelectedRowIndices(new Set());
      setIsDeleteConfirming(false);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to refresh table preview.";
      setResultError(message);
    } finally {
      setIsLoadingResult(false);
    }
  };

  const ensureStructureColumns = async (): Promise<ColumnInfo[]> => {
    if (!selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table) {
      return [];
    }

    const cacheKey = `${selectedDatabase.db_id}:${selectedTable.schema}:${selectedTable.table}`;
    if (structureCacheRef.current?.key === cacheKey) {
      const hasColumnKeyMetadata = structureCacheRef.current.columns.some((column) =>
        Object.prototype.hasOwnProperty.call(column, "column_key")
      );

      if (hasColumnKeyMetadata) {
        return structureCacheRef.current.columns;
      }
    }

    const structure = await fetchTableStructure(selectedDatabase.db_id, selectedTable.schema, selectedTable.table);
    setStructureColumns(structure.columns);
    structureCacheRef.current = {
      key: cacheKey,
      columns: structure.columns,
    };

    return structure.columns;
  };

  const isPrimaryKeyColumn = (column: ColumnInfo) => {
    const key = `${column.column_key || ""}`.trim().toUpperCase();
    return key === "PRI" || key === "PRIMARY" || key === "PRIMARY KEY";
  };

  const handleStartInlineEdit = async (rowIndex: number, column: string) => {
    if (!selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table || isInlineUpdating) {
      return;
    }

    try {
      const columns = await ensureStructureColumns();
      const primaryColumns = columns.filter(isPrimaryKeyColumn);
      if (primaryColumns.length === 0) {
        setResultError("Inline edit requires a table with a primary key.");
        return;
      }

      const row = previewRows[rowIndex] as Record<string, unknown> | undefined;
      if (!row) {
        return;
      }

      const hasPrimaryKeyValues = primaryColumns.every((col) => {
        const value = row[col.column_name];
        return value !== null && value !== undefined && String(value) !== "";
      });

      if (!hasPrimaryKeyValues) {
        setResultError("Inline edit requires row primary key values.");
        return;
      }

      setResultError("");
      setEditingCell({ rowIndex, column });
      setEditingCellValue(getCellDisplayValue(row[column]));
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to prepare inline editing.";
      setResultError(message);
    }
  };

  const handleCancelInlineEdit = () => {
    setEditingCell(null);
    setEditingCellValue("");
  };

  const handleCommitInlineEdit = async () => {
    if (!editingCell || isInlineUpdating || !selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table) {
      return;
    }

    const row = previewRows[editingCell.rowIndex] as Record<string, unknown> | undefined;
    if (!row) {
      handleCancelInlineEdit();
      return;
    }

    const nextValue = editingCellValue;
    const currentValue = getCellDisplayValue(row[editingCell.column]);
    if (nextValue === currentValue) {
      handleCancelInlineEdit();
      return;
    }

    setIsInlineUpdating(true);
    setResultError("");

    try {
      const columns = await ensureStructureColumns();
      const primaryColumns = columns.filter(isPrimaryKeyColumn);
      if (primaryColumns.length === 0) {
        throw new Error("Inline edit requires a table with a primary key.");
      }

      const whereClause = primaryColumns
        .map((col) => `${quoteSqlIdentifier(col.column_name)} = ${toSqlLiteral(row[col.column_name])}`)
        .join(" AND ");

      if (!whereClause) {
        throw new Error("Inline edit requires row primary key values.");
      }

      const engine = getSourceEngine();
      const isMysqlEngine = engine === "mysql" || engine === "mariadb";
      const tableRef = `${quoteSqlIdentifier(selectedTable.schema)}.${quoteSqlIdentifier(selectedTable.table)}`;
      const query = `UPDATE ${tableRef} SET ${quoteSqlIdentifier(editingCell.column)} = ${toSqlLiteral(nextValue)} WHERE ${whereClause}${isMysqlEngine ? " LIMIT 1" : ""}`;
      await runSourceSql(selectedDatabase.db_id, query);

      setResultRows((previous) =>
        previous.map((item, index) => {
          if (index !== editingCell.rowIndex) {
            return item;
          }

          return {
            ...item,
            [editingCell.column]: nextValue,
          };
        })
      );

      handleCancelInlineEdit();
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to update row.";
      setResultError(message);
    } finally {
      setIsInlineUpdating(false);
    }
  };

  const handleDeleteRows = async (indicesToDelete: Set<number>) => {
    if (indicesToDelete.size === 0 || !selectedDatabase?.db_id || !selectedTable?.schema || !selectedTable?.table) {
      return;
    }

    if (!canDeleteRows) {
      setResultError("Delete is available only in table preview mode.");
      return;
    }

    setIsDeleting(true);
    try {
      const rowsToDelete = Array.from(indicesToDelete)
        .map((idx) => resultRows[idx])
        .filter(Boolean);

      const tableRef = `${quoteSqlIdentifier(selectedTable.schema)}.${quoteSqlIdentifier(selectedTable.table)}`;
      const deleteQueries: string[] = [];

      for (const row of rowsToDelete) {
        const whereConditions: string[] = [];
        Object.entries(row as Record<string, unknown>).forEach(([col, val]) => {
          if (val === null || val === undefined) {
			whereConditions.push(`${quoteSqlIdentifier(col)} IS NULL`);
          } else {
			whereConditions.push(`${quoteSqlIdentifier(col)} = ${toSqlLiteral(val)}`);
          }
        });

        if (whereConditions.length > 0) {
          const whereClause = whereConditions.join(' AND ');
          deleteQueries.push(`DELETE FROM ${tableRef} WHERE ${whereClause}`);
        }
      }

      for (const query of deleteQueries) {
        await runSourceSql(selectedDatabase.db_id, query);
      }

      await refreshPreviewRows();
      setContextMenu(null);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unable to delete rows.";
      setResultError(message);
    } finally {
      setIsDeleting(false);
    }
  };

  const handleDuplicateRow = (rowIndex: number) => {
    const rowToDuplicate = previewRows[rowIndex] as Record<string, unknown>;
    const duplicateData: Record<string, string> = {};

    // Iterate over structure columns to ensure all form fields are populated
    structureColumns.forEach(col => {
      // Skip auto-increment and generated columns
      if (col.extra?.includes('auto_increment') || col.column_default?.includes('nextval')) {
        return;
      }

      const val = rowToDuplicate[col.column_name];
      if (val === null || val === undefined) {
        duplicateData[col.column_name] = '';
      } else if (typeof val === 'object') {
        duplicateData[col.column_name] = JSON.stringify(val);
      } else {
        duplicateData[col.column_name] = String(val);
      }
    });

    insertPrefillRef.current = true;
    setEditingRowIndex(null);
    setInsertFormData(duplicateData);
    setViewPanelContent('insert');
    setShowViewPanel(true);
    setContextMenu(null);
  };

  const handleEditRow = (rowIndex: number) => {
    const rowToEdit = previewRows[rowIndex] as Record<string, unknown>;
    const editData: Record<string, string> = {};

    // Iterate over structure columns to ensure all form fields are populated
    structureColumns.forEach(col => {
      const val = rowToEdit[col.column_name];
      if (val === null || val === undefined) {
        editData[col.column_name] = '';
      } else if (typeof val === 'object') {
        editData[col.column_name] = JSON.stringify(val);
      } else {
        editData[col.column_name] = String(val);
      }
    });

    insertPrefillRef.current = true;
    setEditingRowIndex(rowIndex);
    setInsertFormData(editData);
    setViewPanelContent('insert');
    setShowViewPanel(true);
    setContextMenu(null);
  };

  const handleContextMenu = (e: React.MouseEvent, rowIndex: number) => {
    e.preventDefault();
    setContextMenu({ x: e.clientX, y: e.clientY, rowIndex });
    if (!selectedRowIndices.has(rowIndex)) {
      setSelectedRowIndices(new Set([rowIndex]));
    }
  };

  // Close context menus when clicking elsewhere
  useEffect(() => {
    const handleClickOutside = () => {
      setContextMenu(null);
      setRequestContextMenu(null);
    };
    if (contextMenu || requestContextMenu) {
      document.addEventListener('click', handleClickOutside);
      return () => document.removeEventListener('click', handleClickOutside);
    }
  }, [contextMenu, requestContextMenu]);

  // Update select-all checkbox indeterminate state
  useEffect(() => {
    if (selectAllCheckboxRef.current) {
      selectAllCheckboxRef.current.indeterminate = 
        selectedRowIndices.size > 0 && selectedRowIndices.size < previewRows.length;
    }
  }, [selectedRowIndices, previewRows.length]);

  // Clear selection when table changes
  useEffect(() => {
    setSelectedRowIndices(new Set());
    setIsDeleteConfirming(false);
    setTableSort(null);
    setEditingRowIndex(null);
    setEditingCell(null);
    setEditingCellValue("");
  }, [selectedTable]);

  useEffect(() => {
    if (isDeleteConfirming) {
      setIsDeleteConfirming(false);
    }
  }, [sqlText, selectedRowKey, selectedDatabase?.db_id]);

  const handleToggleViewPanel = (content: Exclude<ViewPanelContent, null>) => {
    if (viewPanelContent === content && showViewPanel) {
      setShowViewPanel(false);
      setViewPanelContent(null);
      return;
    }

    setViewPanelContent(content);
    setShowViewPanel(true);
  };

  return (
    <div className="relative h-full w-full overflow-hidden bg-gray-950/50 text-white">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -left-20 -top-28 h-80 w-80 rounded-full bg-cyan-500/10 blur-3xl" />
        <div className="absolute right-0 top-12 h-72 w-72 rounded-full bg-amber-500/10 blur-3xl" />
        <div className="absolute bottom-0 left-1/3 h-80 w-80 rounded-full bg-lime-500/10 blur-3xl" />
        <div className="absolute left-1/2 top-1/5 transform h-64 w-64 rounded-full bg-purple-500/5 blur-3xl" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,_rgba(255,255,255,0.06),_transparent_45%)]" />
      </div>

      <div className="relative z-10 flex h-full flex-col">
        <DatabaseTopBar
          leftPanelTab={leftPanelTab}
          selectedTable={selectedTable}
          showSqlPanel={showSqlPanel}
          showViewPanel={showViewPanel}
          viewPanelContent={viewPanelContent}
          onLeftPanelTabChange={setLeftPanelTab}
          onToggleSqlPanel={() => setShowSqlPanel((previous) => !previous)}
          onToggleViewPanel={handleToggleViewPanel}
        />

        {!selectedDatabase ? (
          <DatabaseEmptyState
            leftPanelTab={leftPanelTab}
            connections={connections}
            isLoadingConnections={isLoadingConnections}
            connectionsError={connectionsError}
            existingQuery={existingQuery}
            onExistingQueryChange={setExistingQuery}
            onRetryConnections={loadConnections}
            getDatabaseHref={(connection) => (connection.db_id !== null ? `/database/${connection.db_id}` : null)}
          />
        ) : (
          <div className="flex flex-1 gap-2 overflow-hidden">
            {leftPanelTab === "requests" ? (
              <RequestsPanel
                requestFilter={requestFilter}
                isLoadingRequests={isLoadingRequests}
                requestsError={requestsError}
                hasSelectedDatabase={Boolean(selectedDatabase)}
                requestFolders={requestFolders}
                requestItems={requestItems}
                filteredRequestFolders={filteredRequestFolders}
                requestsByFolder={requestsByFolder}
                ungroupedRequests={ungroupedRequests}
                selectedRequestId={selectedRequestId}
                inlineEditingItem={inlineEditingItem}
                inlineEditingValue={inlineEditingValue}
                renamingItem={renamingItem}
                requestContextMenu={requestContextMenu}
                onRequestFilterChange={setRequestFilter}
                setInlineEditingItem={setInlineEditingItem}
                setInlineEditingValue={setInlineEditingValue}
                setRenamingItem={setRenamingItem}
                setRequestContextMenu={setRequestContextMenu}
                setRequestsError={setRequestsError}
                onCreateFolder={handleCreateFolder}
                onCreateRequest={handleCreateRequest}
                onRenameFolder={handleRenameFolder}
                onRenameRequest={handleRenameRequest}
                onDeleteFolder={handleDeleteFolder}
                onDeleteRequest={handleDeleteRequest}
                onSelectRequest={handleSelectRequest}
              />
            ) : null}

            {leftPanelTab === "tables" ? (
              <TablesPanel
                schemaFilter={schemaFilter}
                explorerSchemas={explorerSchemas}
                filteredSchemas={filteredSchemas}
                isLoadingExplorer={isLoadingExplorer}
                explorerError={explorerError}
                selectedTable={selectedTable}
                onSchemaFilterChange={setSchemaFilter}
                onSelectTable={handleSelectTable}
              />
            ) : null}

            {leftPanelTab === "sources" ? (
              <aside className="flex w-full max-w-sm flex-col overflow-hidden border-r border-white/10 bg-black/30 p-3">
                <SourcesPanel
                  connections={connections}
                  isLoading={isLoadingConnections}
                  error={connectionsError}
                  query={existingQuery}
                  onQueryChange={setExistingQuery}
                  onRetry={loadConnections}
                  getDatabaseHref={(connection) => (connection.db_id !== null ? `/database/${connection.db_id}` : null)}
                  selectedDatabaseId={selectedDatabase.db_id}
                  type="db"
                />
              </aside>
            ) : null}

            <main className="flex flex-1 flex-col gap-4 overflow-hidden">
              {showSqlPanel ? (
                <CollapsibleSection
                  title={
                    <div className="flex items-center justify-between">
                      <p className="text-sm font-semibold">SQL Console</p>
                      <button
                        className="rounded-md bg-white/10 px-3 py-1 text-xs text-white disabled:cursor-not-allowed disabled:opacity-60"
                        onClick={() => runSql()}
                        disabled={isLoadingResult || !selectedDatabase?.db_id}
                      >
                        {isLoadingResult ? "Running..." : "Run"}
                      </button>
                    </div>
                  }
                  className="rounded-xl border border-white/10 bg-black/5 p-1 mt-3"
                  isOpen={expandSqlPanel}
                  onToggle={(isOpen) => {
                      setExpandSqlPanel(isOpen);
                  }}
                >
                  <div 
                    className="mt-3 w-full overflow-hidden rounded-lg border border-white/10"
                    style={{ height: `${editorHeight}px` }}
                  >
                    <div ref={monacoContainerRef} className="h-full w-full" />
                  </div>
                </CollapsibleSection>
              ) : null}

              <div className="flex-1 overflow-hidden rounded-xl border border-white/10 bg-black/30 py-2 px-3">
                {isLoadingResult || selectedTable || resultRows.length > 0 || resultColumns.length > 0 ? (
                  <>
                    <div className="mb-3 flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        <p className="text-sm font-semibold">
                          {selectedTable ? "Browse Data" : "Query Results"}
                        </p>
                        {selectedRowIndices.size > 0 && (
                          <span className="rounded-full border border-white/40 bg-white/10 px-2 py-1 text-xs text-white">
                            {selectedRowIndices.size} selected
                          </span>
                        )}
                      </div>
                      <div className="flex items-center gap-2">
                        {selectedRowIndices.size > 0 && canDeleteRows ? (
                          isDeleteConfirming ? (
                            <>
                              <button
                                onClick={() => handleDeleteRows(selectedRowIndices)}
                                disabled={isDeleting}
                                className="rounded-md border border-rose-400/40 bg-rose-500/30 px-2 py-1 text-xs text-rose-100 hover:bg-rose-500/40 disabled:opacity-50"
                              >
                                {isDeleting ? "Deleting..." : `Confirm delete (${selectedRowIndices.size})`}
                              </button>
                              <button
                                onClick={() => setIsDeleteConfirming(false)}
                                disabled={isDeleting}
                                className="rounded-md border border-white/20 bg-white/10 px-2 py-1 text-xs text-slate-200 hover:bg-white/20 disabled:opacity-50"
                              >
                                Cancel
                              </button>
                            </>
                          ) : (
                            <button
                              onClick={() => setIsDeleteConfirming(true)}
                              disabled={isDeleting}
                              className="rounded-md border border-rose-400/30 bg-rose-500/10 px-2 py-1 text-xs text-rose-200 hover:bg-rose-500/20 disabled:opacity-50"
                            >
                              Delete
                            </button>
                          )
                        ) : null}
                        {selectedTable ? (
                          <IconButton
                            icon={<FaSyncAlt className={isLoadingResult ? "animate-spin" : ""} />}
                            onClick={handleRefreshResults}
                            disabled={isLoadingResult || isDeleting || !selectedDatabase?.db_id}
                            title="Refresh rows"
                            aria-label="Refresh rows"
                            sizeClassName="h-7 w-7"
                            activeClassName="border-white/20 bg-white/15 text-white"
                            inactiveClassName="border-white/20 bg-white/10 text-slate-200 hover:bg-white/20"
                          />
                        ) : null}
                        <span className="rounded-full border border-white/10 bg-white/5 px-2 py-1 text-xs text-slate-300">{resultMeta || `${previewRows.length} rows`}</span>
                      </div>
                    </div>
                    {resultError ? (
                      <div className="mb-3 rounded-lg border border-rose-400/30 bg-rose-400/10 px-3 py-2 text-xs text-rose-200">{resultError}</div>
                    ) : null}
                    {isLoadingResult ? (
                      <div className="flex h-full items-center justify-center">
                        <div className="rounded-lg border border-white/10 bg-white/5 px-4 py-3 text-center text-sm text-slate-300">
                          Loading rows...
                        </div>
                      </div>
                    ) : previewRows.length === 0 ? (
                      <div className="flex h-full items-center justify-center">
                        <div className="rounded-lg border border-white/10 bg-white/5 px-4 py-3 text-center">
                          <p className="text-sm text-slate-300">No rows found</p>
                          <p className="mt-1 text-xs text-slate-400">This table is empty</p>
                        </div>
                      </div>
                    ) : (
                      <div className="h-full overflow-hidden rounded-lg border border-white/10 bg-black/20 pb-8">
                        <div className="overflow-x-auto h-full">
                          <table className="w-full text-xs">
                            <thead>
                              <tr className="border-b border-white/10 bg-black sticky top-0">
                                <th className="w-10 px-3 py-2 text-left font-semibold">
                                  <input
                                    ref={selectAllCheckboxRef}
                                    type="checkbox"
                                    checked={selectedRowIndices.size > 0 && selectedRowIndices.size === previewRows.length}
                                    onChange={(e) => {
                                      if (e.target.checked) {
                                        setSelectedRowIndices(new Set(previewRows.map((_, i) => i)));
                                      } else {
                                        setSelectedRowIndices(new Set());
                                      }
                                    }}
                                    className="cursor-pointer"
                                  />
                                </th>
                                {hotColumns.map((column) => {
                                  const isSortedColumn = tableSort?.column === column;
                                  return (
                                    <th key={column} className="px-3 py-2 text-left font-semibold">
                                      <button
                                        type="button"
                                        onClick={() => handleSortByColumn(column)}
                                        className="inline-flex items-center gap-1 text-slate-200 hover:text-white"
                                        title={`Sort by ${column}`}
                                      >
                                        <span>{column}</span>
                                        {isSortedColumn ? (
                                          <span className="text-[10px] text-cyan-200">{tableSort?.direction === "asc" ? "▲" : "▼"}</span>
                                        ) : null}
                                      </button>
                                    </th>
                                  );
                                })}
                              </tr>
                            </thead>
                            <tbody>
                              {previewRows.map((row, rowIndex) => (
                                <tr 
                                  key={rowIndex} 
                                  className={`border-b border-white/5 cursor-pointer transition ${
                                    selectedRowIndices.has(rowIndex)
                                      ? 'bg-white/10'
                                      : rowIndex % 2 === 0 ? 'bg-black/50 hover:bg-white/5' : 'hover:bg-white/5'
                                  }`}
                                  onContextMenu={(e) => handleContextMenu(e, rowIndex)}
                                >
                                  <td className="w-10 px-3">
                                    <input
                                      type="checkbox"
                                      checked={selectedRowIndices.has(rowIndex)}
                                      onChange={() => toggleRowSelection(rowIndex)}
                                      className="cursor-pointer"
                                    />
                                  </td>
                                  {hotColumns.map((column) => {
                                    const value = (row as Record<string, unknown>)[column];
                                    const displayValue = getCellDisplayValue(value);
                                    const isEditingCell =
                                      editingCell?.rowIndex === rowIndex && editingCell?.column === column;
                                    
                                    return (
                                      <td
                                        key={`${rowIndex}-${column}`}
                                        className="px-3 py-1 font-mono text-slate-300 max-w-xs truncate hover:border hover:border-white/20"
                                        title={displayValue}
                                        onDoubleClick={() => handleStartInlineEdit(rowIndex, column)}
                                      >
                                        {isEditingCell ? (
                                          <input
                                            autoFocus
                                            value={editingCellValue}
                                            onChange={(event) => setEditingCellValue(event.target.value)}
                                            onKeyDown={(event) => {
                                              if (event.key === "Enter") {
                                                event.preventDefault();
                                                handleCommitInlineEdit();
                                              }

                                              if (event.key === "Escape") {
                                                event.preventDefault();
                                                event.currentTarget.setAttribute("data-skip-commit", "1");
                                                handleCancelInlineEdit();
                                              }
                                            }}
                                            onBlur={(event) => {
                                              const skipCommit = event.currentTarget.getAttribute("data-skip-commit") === "1";
                                              if (skipCommit) {
                                                return;
                                              }
                                              handleCommitInlineEdit();
                                            }}
                                            disabled={isInlineUpdating}
                                            className="w-full rounded border border-cyan-300/50 bg-black/80 px-1 py-0.5 text-xs text-white outline-none"
                                          />
                                        ) : (
                                          displayValue || <span className="text-slate-500 italic">null</span>
                                        )}
                                      </td>
                                    );
                                  })}
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        </div>
                      </div>
                    )}
                  </>
                ) : (
                  <div className="flex h-full items-center justify-center">
                    <div className="rounded-lg border border-white/10 bg-white/5 px-4 py-3 text-center text-sm text-slate-300">
                      Select a table from the left panel
                    </div>
                  </div>
                )}

                {/* Context Menu */}
                {contextMenu && contextMenu.rowIndex !== undefined && (
                  <div
                    className="fixed z-50 rounded-lg border border-white/10 bg-black/90 text-xs shadow-xl"
                    style={{
                      left: `${contextMenu.x}px`,
                      top: `${contextMenu.y}px`,
                    }}
                  >
                    <button
                      onClick={() => handleDeleteRows(new Set([contextMenu.rowIndex]))}
                      disabled={isDeleting}
                      className="block w-full px-3 py-2 text-left text-rose-200 hover:bg-rose-500/20 disabled:opacity-50"
                    >
                      {isDeleting ? "Deleting..." : "Delete"}
                    </button>
                    <button
                      onClick={() => handleDuplicateRow(contextMenu.rowIndex)}
                      className="block w-full px-3 py-2 text-left text-slate-200 hover:bg-white/10"
                    >
                      Duplicate
                    </button>
                    <button
                      onClick={() => handleEditRow(contextMenu.rowIndex)}
                      className="block w-full px-3 py-2 text-left text-slate-200 hover:bg-white/10 rounded-b-lg"
                    >
                      Edit
                    </button>
                  </div>
                )}
              </div>
            </main>

            {showViewPanel && viewPanelContent ? (
              <aside className={`flex flex-col overflow-hidden border-l border-white/10 bg-black/30 p-4 ${
                viewPanelContent === "structure" ? "w-full max-w-2xl" : viewPanelContent === "search" ? "w-full max-w-lg" : "w-full max-w-md"
              }`}>
                {viewPanelContent === "structure" ? (
                  <StructurePanel
                    selectedTable={selectedTable}
                    structureColumns={structureColumns}
                    isLoading={isLoadingStructure}
                    error={structureError}
                  />
                ) : viewPanelContent === "insert" ? (
                  <InsertPanel
                    selectedTable={selectedTable}
                    structureColumns={structureColumns}
                    isLoading={isLoadingStructure}
                    error={structureError}
                    formData={insertFormData}
                    insertError={insertError}
                    insertSuccess={insertSuccess}
                    isInserting={isInserting}
                    isEditMode={editingRowIndex !== null}
                    onChange={handleInsertFormChange}
                    onSubmit={handleInsertSubmit}
                    onReset={handleInsertReset}
                  />
                ) : viewPanelContent === "search" ? (
                  <SearchPanel
                    selectedTable={selectedTable}
                    structureColumns={structureColumns}
                    isLoading={isLoadingStructure}
                    error={structureError}
                    filters={searchFilters}
                    searchError={searchError}
                    isSearching={isSearching}
                    onFilterChange={handleSearchFilterChange}
                    onClearFilter={handleClearSearchFilter}
                    onSubmit={handleSearchSubmit}
                    onClearAll={handleClearSearchAll}
                  />
                ) : null}
              </aside>
            ) : null}
          </div>
        )}
      </div>
    </div>
  );
};

export default DatabasePage;
